- name: Add node apt key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Copy nodesource list
  copy: src=nodesource.list dest=/etc/apt/sources.list.d/

- name: Install packages
  apt: name={{ item }} state=present  update_cache=yes cache_valid_time=86400
  with_items:
    - git
    - nodejs

- name: Checkout repo
  git: repo=https://github.com/Jonnymcc/my-blog.git dest={{ blog_dir }} force=yes
  notify: restart blog

- name: Install npm packages
  npm: path={{ blog_dir }}
  notify: restart blog

- name: Upload upstart conf
  template: src=upstart.j2 dest=/etc/init/blog.conf
  notify: restart blog

- name: Upload config for mongo-express
  copy: src=mongo-express-config.js dest={{ blog_dir }}/node_modules/mongo-express/config.js
  notify: restart mongo-express

- name: Upload mongo-express upstart conf
  template: src=upstart-mongo-express.j2 dest=/etc/init/mongo-express.conf
  notify: restart mongo-express

- name: Start services
  service: name={{ item }} state=started
  with_items:
    - blog
    - mongo-express

- name: Configure logrotate for blog access log
  copy: src=logrotate.conf dest=/etc/logrotate.d/blog
