- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - nodejs
    - npm

- name: Checkout repo
  git: repo=https://github.com/Jonnymcc/my-blog.git dest={{ blog_dir }} force=yes
  notify: restart blog

- name: Install npm packages
  npm: path={{ blog_dir }}

- name: Upload upstart conf
  template: src=upstart.j2 dest=/etc/init/blog.conf
  notify: restart blog

- name: Start blog
  service: name=blog state=started

- name: Configure logrotate for blog access log
  copy: src=logrotate.conf dest=/etc/logrotate.d/blog
